# 1. Waypoints for the can sorting task
-
  # 1.1. Approach the can
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.11500076, -0.20500796, 0.92999208, 0.99984902, 0.00004765, -0.00002402, -0.00003580]
  left_hand_bool: 0
  right_hand_bool: 0
-
  # 1.2. Grasp the can
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.11500076, -0.20500796, 0.92999208, 0.99984902, 0.00004765, -0.00002402, -0.00003580]
  left_hand_bool: 0
  right_hand_bool: 1
-
  # 1.3. lift up
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.11500076, -0.20500796, 0.98, 0.99984902, 0.00004765, -0.00002402, -0.00003580]
  left_hand_bool: 0
  right_hand_bool: 1
-
  # 1.4. Move the bottle toward the top of the target basket (red)
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.23998797, -0.15493149, 0.98986787, 0.99984890, -0.00009122, 0.00045890, -0.00020878]
  left_hand_bool: 0
  right_hand_bool: 1
-
  # 1.5. Move down
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.23995677, -0.15493181, 0.94485849, 0.99984890, -0.00008668, 0.00049764, -0.00023014]
  left_hand_bool: 0
  right_hand_bool: 1
-
  # 1.6. Release the can
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.23995677, -0.15493181, 0.94485849, 0.99984890, -0.00008668, 0.00049764, -0.00023014]
  left_hand_bool: 0
  right_hand_bool: 0
-
  # 1.7. Back to a prepared position
  left_arm_eef: [-0.05000006, 0.15349832, 0.71199965, 0.707, 0.0, 0.707, 0.0]
  right_arm_eef: [0.05000069, -0.32000598, 1.04999280, 0.99984896, 0.00004716, -0.00002606, -0.00003251]
  left_hand_bool: 0
  right_hand_bool: 0